### ISSUE TITLE
Black List mode option does not work on Android

### ISSUE THREAD

**Issue by MicroBeast** [ray-lothian/UserAgent-Switcher#28] opened 2019-01-12 12:38 UTC
- Android 6.0.1, 7.1.1, 7.1.2. Samsung SM-A300FU, Samsung SM-T555, Xiaomi Redmi 4A respectively.
- Android Firefox 64.0
- Android Yandex Browser with Protect 18.11.979 (the only Chromium based that support Chrome extensions).
- User-Agent Switcher and Manager 0.2.6.

The Black-list mode option simply does not work as intended. White-list mode and Custom mode do work as intended.

Thank you.

**Comment by ray-lothian** [comment] 2019-03-13 09:26
Duplicate of https://github.com/ray-lothian/UserAgent-Switcher/issues/29. Thanks for the report. Will be fixed by the next release.

**Closed by ray-lothian** 2019-03-13 09:26 UTC
