### ISSUE TITLE
Seperate option for cuatom mode

### ISSUE THREAD

**Issue by williamsp** [ray-lothian/UserAgent-Switcher#8] opened 2018-01-10 17:01 UTC
I still want to use the blacklist/whitelist mode while using custom mode. So if a website is registered in custom mode, it will use the custom user agent for that website (override the selected user agent). Otherwise, use the selected global user agent.

**Comment by ray-lothian** [comment] 2018-08-15 12:12
Duplicate of FAQ9? https://add0n.com/useragent-switcher.html

**Closed by ray-lothian** 2018-08-15 12:12 UTC
